### ISSUE TITLE
NuGet Package Deprecation

### ISSUE THREAD

**Issue by BernhardMaier** [SoftFluent/EntityFrameworkCore.DataEncryption#65]
Today we discovered that the NuGet package has been marked as “deprecated” on nuget.org and is no longer listed there. This means that we are currently unable to update the NuGet packages in our application.

Are there any reasons why the package is no longer maintained?

![grafik](https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/assets/46556453/a0352140-bc31-42d0-879d-617ea9ede4fb)
[NuGet Page](https://www.nuget.org/packages/EntityFrameworkCore.DataEncryption)

**Comment by Uli-Armbruster** [comment]
That would be indeed interesting. What is the status?

**Comment by JeffreyHiscox** [comment]
Also curious about this?

**Comment by BernhardMaier** [comment]
We found out that the repo owner `Retired from open-source` and may not responde to our questions in this issue:
![grafik](https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/assets/46556453/9fdb8902-c4ac-4292-9e35-607635d6fde7)

**Comment by lukasschachner** [comment]
That's very sad, @Eastrall. Can we support you in maintaining this package in any way?

**Comment by nielsNocore** [comment]
did anyone have a solution for this, an alternatives?

**Comment by BernhardMaier** [comment]
We found two possible alternatives that seem to be "clones" of Eastralls package or at least are based on it:
-  [V6.EntityFrameworkCore.DataEncryption](https://www.nuget.org/packages/V6.EntityFrameworkCore.DataEncryption)
-  [EntityFrameworkCore.Crypto.DataEncryption](https://www.nuget.org/packages/EntityFrameworkCore.Crypto.DataEncryption)

Both have almost the same readme as Eastralls and the first package also points to Eastralls repository. We haven't changed our dependencies or tested these packages yet, but maybe it's a quick and sufficient solution for you and you can take a look at them.

In the long term, an official fork of Eastrall's package or becoming a maintainer would be the best solutions, also in order to continue his work in a sustainable and worthy manner.

**Comment by XarSoft** [comment]
The package is now maintained by SoftFluent. It is no longer deprecated.

**Comment by XarSoft** [comment]
Fixed
